:concurrency: 5
:queues:
  - default
  - chats
  - messages
:redis:
  :timeout: 10


:scheduler:
  :schedule:
    update_counts_worker:
      cron: "0 * * * *" # Runs every hour
      class: "UpdateCountsWorker"
